# Generated by Django 4.2.5 on 2023-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_vendor_purchase_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
